### ISSUE TITLE
Problem with update of block_context.block_timestamp

### ISSUE THREAD

**Issue by mikiw** [starkware-libs/blockifier#1145]
I was trying to solve this issue https://github.com/0xSpaceShard/starknet-devnet-rs/pull/251 and I did it with blockifier v0.3.0-rc0 but with version v0.4.0-rc3 updating block_context.block_timestamp was not possible anymore and I'm still getting the same timestamp 1072023 which is default value of `pub const CURRENT_BLOCK_TIMESTAMP: u64 = 1072023;`

**Comment by FabijanC** [comment]
I'd like to add that both the `get_block_timestamp` Starknet syscall (marked as deprecated in your repo) and the `block_timestamp` property of `block_info` seem to return `1072023`.

**Comment by mikiw** [comment]
It was problem on our side, we used `execute_directly()`instead of `execute()`
